"""two

Revision ID: 11a306f7811d
Revises: 46f47ae68938
Create Date: 2021-03-26 08:01:10.104017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a306f7811d'
down_revision = '46f47ae68938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('author', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'author')
    # ### end Alembic commands ###
