"""first

Revision ID: 46f47ae68938
Revises: 
Create Date: 2021-03-25 21:20:32.813027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f47ae68938'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_resurs', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resurs_id'), 'resurs', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pubdate', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('media', sa.String(length=100), nullable=True),
    sa.Column('full_item', sa.JSON(), nullable=True),
    sa.Column('resurs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resurs_id'], ['resurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_resurs_id'), table_name='resurs')
    op.drop_table('resurs')
    # ### end Alembic commands ###
